### ISSUE TITLE
It is recommended to add desktop lyrics

### ISSUE THREAD

**Issue by zaprtqa** [qier222/YesPlayMusic#1631]
It is recommended to add desktop lyrics

**Comment by pan93412** [comment]
I see your point. However, we decided to not accept this idea according to the previous discussion and implementation.

There is an unofficial YesPlayMusic fork in GitHub called “YesPlayMusicOSD.” It includes the float lyric function; nonetheless, it may not the latest — in other words, it may has some bugs that has been fixed in our version.

Sorry for not accepting your idea. You are still welcome to contribute other features request, bug reports, and code improvement.
