### ISSUE TITLE
打包为Flatpak应用并提交至Flathub分发

### ISSUE THREAD

**Issue by Kruegerrr** [qier222/YesPlayMusic#1738]
经由Flathub分发的Flatpak应用便于集中更新，可提供更佳的linux跨发行版体验。

**Comment by tinywrkb** [comment]
对不起我的中文不好，so I'll go with English.
[This is my Initial Flatpak packaging](https://github.com/tinywrkb/flathub/blob/com.github.qier222.YesPlayMusic/com.github.qier222.YesPlayMusic.yaml) which is in a `flathub` repo branch with accordance to the packaging submission guidelines.

This is a proof-of-concept and an example, and is not completely ready for submission. Currently, I prefer using the web browser, so I won't submit the app myself. Also, it always much preferable that the developer(s) will submit and maintainer the app.

There are two possible methods of packaging an Electron application as a Flatpak: building from source or repackaging a binary release.  
Repackaging is the easy solution, it ships the same release built and tested by the developer, and as we don't compile Electron or using a common (to multiple applications) Electron binaries (like Arch Linux does), we might gain nothing by building from source.

In this case, Electron release is too old, and I suspect that it was built with HarfBuzz<3.0.0, as Noto CJK Variable OTCs are broken (needs at least Electron 14 to be rendered correctly), so I went ahead included support from building from source, which was a bit more complicated than what I was hoping for, and that due to `sharp`.

There are a few notes in the packaging manifest, and you're welcome to ask if you need clarifications and more details.  

In the source build, app stays unpacked and `app.asar` is not generated, as we have file-based deduplication in Flatpak, so maybe this will help limit updates' download size and disk writes.

The description entry in the AppStream MetaInfo is empty, so whoever submit the app will need to fill it, and I haven't verified it (`$ appstream-util ...`).

While it should be obvious, `package.json` and `yarn.lock` were added as I updated to Electron 18, and you should drop them if decided to stay with the officially supported version 13.

**Comment by NEOVALI** [comment]
我打包了一个，等会儿搞

**Comment by NEOVALI** [comment]
https://github.com/flathub/flathub/pull/3700
等flathub 审核了

**Comment by NEOVALI** [comment]
https://github.com/flathub/flathub/pull/3702

**Comment by NEOVALI** [comment]
@Kruegerrr 已上架flathub
