### ISSUE TITLE
YesPlayMusic还在维护吗？

### ISSUE THREAD

**Issue by liukenny961** [qier222/YesPlayMusic#876]
如题，感觉好久都没更新了，代码也是几个月前的，Issue里大家提的问题开发者也没回复……

**Comment by 11006281** [comment]
如果项目主比较没有时间维护的话，我想建议项目主将权力下放，可以让这个专案来做到社区维护

**Comment by liukenny961** [comment]
我也这么觉得，社区的话还可以集思广益，汇集更多人的想法与建议 。@qier222

**Comment by qier222** [comment]
最近在忙工作和新的开源项目，等有空的时候会合并pr和修bug

**Comment by lanmanck** [comment]
建议项目主将权力下放。
可以增加在线tv播放功能吗？m3u8的

**Comment by JoeyYoung1997** [comment]
我启动了electron:serve和netease_api的start，项目会报错(node:17376) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
(Use `electron --trace-deprecation ...` to show where the warning was created)
是不是有的包太老了
